#!/bin/bash
# This script was initially created by YuriAlek (https://gitlab.com/YuriAlek).
# I merely stole and modified it.
## Check if the script was executed as root
[[ "$EUID" -ne 0 ]] && echo "Please run as root" && exit 1

##################
# Detach devices #
##################

## Kill the Display Manager
systemctl stop lightdm

## Kill the console
echo 0 > /sys/class/vtconsole/vtcon0/bind
echo 0 > /sys/class/vtconsole/vtcon1/bind
echo efi-framebuffer.0 > /sys/bus/platform/drivers/efi-framebuffer/unbind

## Detach the GPU
virsh nodedev-detach $VIRSH_GPU
virsh nodedev-detach $VIRSH_GPU_AUDIO

## Load vfio
modprobe vfio-pci

sleep 1



############
# Start VM #
############

virsh start win10
sleep 5
# Wait for the VM to finish
while [[ $(pgrep qemu-system) ]]; do
	sleep 5
done



####################
# Reattach devices #
####################
echo "VM stopped, reattaching devices"
## Unload vfio
modprobe -r vfio-pci
modprobe -r vfio_iommu_type1
modprobe -r vfio

## Reattach the GPU
virsh nodedev-reattach $VIRSH_GPU_AUDIO > /dev/null 2>&1
virsh nodedev-reattach $VIRSH_GPU > /dev/null 2>&1

## Reload the framebuffer and console
echo 1 > /sys/class/vtconsole/vtcon0/bind
nvidia-xconfig --query-gpu-info > /dev/null 2>&1
echo "efi-framebuffer.0" > /sys/bus/platform/drivers/efi-framebuffer/bind

## Reload the Display Manager
systemctl start lightdm
